[package]
name = "autosar-xsd-mangler"
version = "0.7.0"
authors = ["Daniel Thaler <daniel@dthaler.de>"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "autosar xsd processor for autosar-data-specification"

[dependencies]
xml-rs = "0.8"
rustc-hash = "2.0.0"